apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: hello-world
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    persistentvolumeclaims: "0"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
